FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    && rm -rf /var/lib/apt/lists/*

COPY ..

RUN pip install --no-cache-dir -e.

# used ports
EXPOSE 8501
EXPOSE 9999

CMD ["python", "app/main.py"]


